# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamAsgardianTodoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "RealmSwift"

  # Pods for TeamAsgardianTodoList

  target 'TeamAsgardianTodoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeamAsgardianTodoListUITests' do
    # Pods for testing
  end

end
